### ISSUE TITLE
Change ownership

### ISSUE THREAD

**Issue by ADBeveridge** [zesterer/journalnext#11]
I would like to port this to GTK4, plus add the listed features in the README.md, but pull requests are a pain for comprehensive work like this, is it possible that I clone it to my own account then you delete the it from your account? (It would be messy to have another version of Journal/Vulcan, making it Journal/Vulcan/(new)Vulcan)

**Comment by ADBeveridge** [comment]
I've initialized it here: https://github.com/ADBeveridge/vulcan

**Comment by zesterer** [comment]
Hello! You're very welcome to clone it and do what you will with it. I've moved on from Vala quite some time ago unfortunately. If you make substantial changes, I can transfer ownership of the repository to you too.

**Comment by ADBeveridge** [comment]
Sounds good!
