### ISSUE TITLE
Implement shortcuts

### ISSUE THREAD

**Issue by donadigo** [zesterer/journalnext#5]
There aren't any shortcuts like: save, open, show sidebar, preferences etc.  
I have put together some code for you ;)
window.vala: http://pastebin.com/QWPKjfbZ
tabbox.vala: http://pastebin.com/uNwF60e3

**Comment by zesterer** [comment]
Thanks. I've actually been working on this in recent hours, it was the next thing on my todo list.

**Comment by zesterer** [comment]
Ok, this is now all done and pushed to git. Thanks for your help, I've included you in the AUTHORS file under 'special credit'.

**Comment by donadigo** [comment]
Thanks. ;)
