### ISSUE TITLE
created a package for archlinux

### ISSUE THREAD

**Issue by ghost** [zesterer/journalnext#7]
Just for your information:
https://aur.archlinux.org/packages/vulcan-editor-git/

a license file would be nice :)
If you have anny suggestions please let me know.

**Comment by Pi3R1k** [comment]
Why add gio-sharp to AUR package ?

Work nice without !

**Comment by ghost** [comment]
Ah, you're right. Was a c/p mistake for the gio dependency, which is (as far as I know) supported through glib.
-> updated

**Comment by zesterer** [comment]
Thank you very much!

Just to make you aware, I'll be beginning to build it around make at some point in the near future, so you may need to rebuild the package.

Thanks for making this.

**Comment by zesterer** [comment]
Also I'd just like to point out that vulcan is touchy about which VTE version is has when compiling since the API changed significantly. It needs 2.90.

**Comment by ghost** [comment]
thx for the info. I'll keep an eye on it :)
